In [2]:
# Importing needed libraries
import pandas as pd
import numpy as np
import dask.dataframe as dd
'''import sklearn # sci-kitlean
import toolz
import torch'''

'import sklearn # sci-kitlean\nimport toolz\nimport torch'

In [3]:
# Read the JSON file into a pandas DataFrame
daily_metrics = pd.read_json('data-folder\daily_metrics.jsonl', lines=True)
monthly_metrics = pd.read_json('data-folder\monthly_metrics.jsonl', lines=True)
transactions = pd.read_json('data-folder\_transactions.jsonl', lines=True)
# transactions = dd.read_json("data-folder\_transactions.jsonl", lines=True)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\m'
<>:4: SyntaxWarning: invalid escape sequence '\_'
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\m'
<>:4: SyntaxWarning: invalid escape sequence '\_'
C:\Users\hikar\AppData\Local\Temp\ipykernel_30588\1753022178.py:2: SyntaxWarning: invalid escape sequence '\d'
  daily_metrics = pd.read_json('data-folder\daily_metrics.jsonl', lines=True)
C:\Users\hikar\AppData\Local\Temp\ipykernel_30588\1753022178.py:3: SyntaxWarning: invalid escape sequence '\m'
  monthly_metrics = pd.read_json('data-folder\monthly_metrics.jsonl', lines=True)
C:\Users\hikar\AppData\Local\Temp\ipykernel_30588\1753022178.py:4: SyntaxWarning: invalid escape sequence '\_'
  transactions = pd.read_json('data-folder\_transactions.jsonl', lines=True)

In [4]:
# Display the first few rows of the daily_metrics DataFrame to verify
daily_metrics.head()

,tenant/id,daily/time,app/name,app/id,daily/metric,daily/label,daily/value
0,DEMO,2024-06-01T00:00:00,Selene Customer Warehouse,SELENE,cost,Cost,158758.25
1,DEMO,2024-06-01T00:00:00,Selene Customer Warehouse,SELENE,value,Value,4646.10
2,DEMO,2024-06-01T00:00:00,Selene Customer Warehouse,SELENE,data_used,Data Used,4646.10
3,DEMO,2024-06-01T00:00:00,Selene Customer Warehouse,SELENE,data_sent,Data Sent,4646.10
4,DEMO,2024-06-01T00:00:00,Selene Customer Warehouse,SELENE,requests_made,Requests Made,5490.00

In [5]:
daily_metrics.describe()

         daily/value
count  666855.000000
mean     2144.657302
std     21517.766368
min         0.000000
25%         0.000000
50%         0.456095
75%        60.758229
max    433440.000000

In [6]:
monthly_metrics.columns

Index(['tenant/id', 'monthly/created', 'app/name', 'app/id', 'monthly/metric',
       'monthly/label', 'monthly/value'],
      dtype='object')

In [7]:
transactions.columns

Index(['tenant/id', 'transaction/consumer/id', 'transaction/consumer/name',
       'transaction/supplier/id', 'transaction/supplier/name',
       'transaction/data', 'transaction/cost', 'transaction/time',
       'transaction/response', 'transaction/id'],
      dtype='object')

In [8]:
transactions['tenant/id'].value_counts()

tenant/id
DEMO    7254656
Name: count, dtype: int64

In [9]:
daily_metrics['tenant/id'].value_counts()

tenant/id
DEMO    666855
Name: count, dtype: int64

In [10]:
#dropping tenant/id column from dataframes because all same
daily_metrics.drop('tenant/id', axis=1, inplace=True)
monthly_metrics.drop('tenant/id', axis=1, inplace=True)
transactions.drop('tenant/id', axis=1, inplace=True)

In [11]:
daily_metrics.shape, monthly_metrics.shape, transactions.shape

((666855, 6), (18270, 6), (7254656, 9))

In [ ]:
print("Data Types for Daily metrics:\n" + str(daily_metrics.dtypes) + "\n\nData Types for Monthly metrics:\n" + str(daily_metrics.dtypes) + "\n\nData Types for Transactions:\n" + str(transactions.dtypes))

Data Types for Daily/Monthly metrics:
daily/time       object
app/name         object
app/id           object
daily/metric     object
daily/label      object
daily/value     float64
dtype: object

Data Types for Transactions:
transaction/consumer/id       object
transaction/consumer/name     object
transaction/supplier/id       object
transaction/supplier/name     object
transaction/data             float64
transaction/cost             float64
transaction/time              object
transaction/response          object
transaction/id                object
dtype: object

In [13]:
# Display the first few rows of the monthly_metrics DataFrame to verify
monthly_metrics.head()

,monthly/created,app/name,app/id,monthly/metric,monthly/label,monthly/value
0,2024-08-01T00:00:00,Selene Customer Warehouse,SELENE,cost,Cost,1219070.80
1,2024-08-01T00:00:00,Selene Customer Warehouse,SELENE,value,Value,35701.05
2,2024-08-01T00:00:00,Selene Customer Warehouse,SELENE,data_used,Data Used,35701.05
3,2024-08-01T00:00:00,Selene Customer Warehouse,SELENE,data_sent,Data Sent,35701.05
4,2024-08-01T00:00:00,Selene Customer Warehouse,SELENE,requests_made,Requests Made,41964.00

In [14]:
# Display the first few rows of the transactions DataFrame to verify
transactions.head()

,transaction/consumer/id,transaction/consumer/name,transaction/supplier/id,transaction/supplier/name,transaction/data,transaction/cost,transaction/time,transaction/response,transaction/id
0,SELENE,Selene Customer Warehouse,AWS,Amazon Web Services,0.30,41.5,2024-06-01 00:00:00,success,t0x78b44bd3-GWVR7-O9HZF
1,SELENE,Selene Customer Warehouse,DBRCKS,Databricks,0.45,49.8,2024-06-01 00:00:00,success,t0x78b44bd3-GWVR7-O9HZF
2,SELENE,Selene Customer Warehouse,SNWFLK,Snowflake,0.90,24.9,2024-06-01 00:00:00,success,t0x78b44bd3-GWVR7-O9HZF
3,FRDETCT,Fraud Detection System,SELENE,Selene Customer Warehouse,1.65,116.2,2024-06-01 00:00:00,success,t0x78b44bd3-GWVR7-O9HZF
4,HMFRP,Hermes Fast Release Platform,AZURE,Microsoft Azure,0.15,16.6,2024-06-01 00:00:00,success,t0x78b44bd3-GWVR7-O9HZF

In [15]:
transactions['transaction/response'].value_counts()

transaction/response
success    7254656
Name: count, dtype: int64

In [16]:
transactions.drop('transaction/response', axis=1, inplace=True)